#!/bin/bash
n1=$((RANDOM % 10000))
n2=$((RANDOM % 10000))
n3=$((RANDOM % 10000))

name=$(printf "tko-%04d-%04d-%04d" $n1 $n2 $n3)
echo setting minion name to $name

echo $name > /etc/salt/minion_id
echo $name > /etc/hostname
sed -i "s/127.0.1.1.*/127.0.1.1\t$name/g" /etc/hosts
reboot 'now'
